version: 2

builds:
  - binary: grant
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X github.com/aaearon/grant-cli/cmd.version={{.Version}}
      - -X github.com/aaearon/grant-cli/cmd.commit={{.ShortCommit}}
      - -X github.com/aaearon/grant-cli/cmd.buildDate={{.CommitDate}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
