name: Bug Report
description: Report a bug or unexpected behavior in grant-cli
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the following information to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened and what did you expect to happen?
      placeholder: Describe the bug and the expected behavior
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command
      description: The exact command that triggered the bug
      placeholder: "Example: grant --verbose azure subscription-reader"
      render: shell
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Error Output
      description: The error message or unexpected output you received
      placeholder: Paste the error message or output here
      render: shell
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Grant Version
      description: Output of `grant version`
      placeholder: "Example: grant v1.0.0 (commit: abc123, built: 2026-02-10)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows (WSL)
        - Windows (native)
        - Other
    validations:
      required: true

  - type: textarea
    id: verbose-output
    attributes:
      label: Verbose Output (Recommended)
      description: |
        Run the command with `--verbose` flag and paste the output. This helps us diagnose the issue faster.
        **Important:** Redact any tokens, passwords, or email addresses.
      placeholder: "Paste output from: grant --verbose <your-command>"
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have redacted any sensitive information (tokens, passwords, emails)
          required: true
