package cmd

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/aaearon/grant-cli/internal/cache"
	"github.com/aaearon/grant-cli/internal/k8s"
	"github.com/spf13/cobra"
)

// execInfoEnvVar is the environment variable kubectl sets for exec credential
// plugins. It carries the requested apiVersion and whether stdin is available.
const execInfoEnvVar = "KUBERNETES_EXEC_INFO"

// supportedExecCredentialAPIVersions are the client-go exec plugin API versions
// grant answers. The response apiVersion always echoes the request.
var supportedExecCredentialAPIVersions = map[string]bool{
	"client.authentication.k8s.io/v1beta1": true,
	"client.authentication.k8s.io/v1":      true,
}

// kubeExecInfo is the subset of KUBERNETES_EXEC_INFO grant reads.
type kubeExecInfo struct {
	APIVersion string `json:"apiVersion"`
	Kind       string `json:"kind"`
	Spec       struct {
		Interactive bool `json:"interactive"`
	} `json:"spec"`
}

// execCredentialFlags are the cluster identifiers embedded in the kubeconfig
// exec stanza.
type execCredentialFlags struct {
	csp            string
	fqdn           string
	roleID         string
	organizationID string
	namespace      string
}

// newK8sExecCredentialCommand creates the hidden kubectl credential plugin command.
func newK8sExecCredentialCommand(runFn func(*cobra.Command, []string) error) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "exec-credential",
		Short:  "kubectl credential plugin (invoked by kubectl, not by hand)",
		Long: `Emit a kubectl ExecCredential for an SCA-eligible cluster.

This command implements the client.authentication.k8s.io exec plugin protocol.
kubectl invokes it via the exec stanza in a kubeconfig generated by
'grant k8s kubeconfig'. It writes nothing to stdout but the ExecCredential JSON.`,
		Hidden:        true,
		Args:          cobra.NoArgs,
		SilenceErrors: true,
		SilenceUsage:  true,
		RunE:          runFn,
	}

	cmd.Flags().String("csp", "", "Cloud provider: aws, azure")
	cmd.Flags().String("fqdn", "", "Cluster API endpoint FQDN")
	cmd.Flags().String("role-id", "", "Cloud role ID to elevate")
	cmd.Flags().String("organization-id", "", "Azure Entra directory (tenant) ID or AWS organization ID")
	cmd.Flags().String("namespace", "", "Kubernetes namespace (Azure namespace-scoped targets)")

	return cmd
}

// NewK8sExecCredentialCommand creates the production exec-credential command.
func NewK8sExecCredentialCommand() *cobra.Command {
	return newK8sExecCredentialCommand(func(cmd *cobra.Command, args []string) error {
		svc, err := bootstrapK8sService()
		if err != nil {
			return err
		}
		return runK8sExecCredential(cmd, svc, defaultCredentialCache(), os.Getenv(execInfoEnvVar))
	})
}

// defaultCredentialCache returns the on-disk ExecCredential cache, or nil when
// the cache directory cannot be resolved (credentials are then never cached).
func defaultCredentialCache() *k8s.CredentialCache {
	dir, err := cache.CacheDir()
	if err != nil {
		return nil
	}
	return k8s.NewCredentialCache(dir)
}

// runK8sExecCredential emits the ExecCredential JSON on stdout and nothing else.
func runK8sExecCredential(
	cmd *cobra.Command,
	provider clusterCredentialProvider,
	credCache *k8s.CredentialCache,
	rawExecInfo string,
) error {
	info, err := parseExecInfo(rawExecInfo)
	if err != nil {
		return err
	}

	flags := parseExecCredentialFlags(cmd)
	if strings.TrimSpace(flags.fqdn) == "" {
		return errors.New("--fqdn is required; regenerate your kubeconfig with 'grant k8s kubeconfig'")
	}
	if _, err := k8s.NormalizeCSP(flags.csp); err != nil {
		return err
	}

	key := k8s.CredentialKey{
		CSP:       flags.csp,
		FQDN:      flags.fqdn,
		RoleID:    flags.roleID,
		Namespace: flags.namespace,
	}

	if credCache != nil {
		if cred, ok := credCache.Get(key); ok {
			log.Info("Reusing cached cluster credential for %s", flags.fqdn)
			return writeExecCredential(cmd, cred, info.APIVersion)
		}
	}

	ctx, cancel := context.WithTimeout(context.Background(), apiTimeout)
	defer cancel()

	cred, err := provider.ExecCredential(ctx, k8s.ExecCredentialParams{
		CSP:            flags.csp,
		FQDN:           flags.fqdn,
		RoleID:         flags.roleID,
		OrganizationID: flags.organizationID,
		Namespace:      flags.namespace,
		Interactive:    info.Spec.Interactive,
		Diagnostics:    verbose,
	})
	if err != nil {
		return err
	}

	if credCache != nil {
		if err := credCache.Put(key, cred); err != nil {
			log.Info("Failed to cache cluster credential: %v", err)
		}
	}

	return writeExecCredential(cmd, cred, info.APIVersion)
}

func parseExecCredentialFlags(cmd *cobra.Command) execCredentialFlags {
	var f execCredentialFlags
	f.csp, _ = cmd.Flags().GetString("csp")
	f.fqdn, _ = cmd.Flags().GetString("fqdn")
	f.roleID, _ = cmd.Flags().GetString("role-id")
	f.organizationID, _ = cmd.Flags().GetString("organization-id")
	f.namespace, _ = cmd.Flags().GetString("namespace")
	return f
}

// parseExecInfo reads KUBERNETES_EXEC_INFO and validates the requested apiVersion.
func parseExecInfo(raw string) (*kubeExecInfo, error) {
	if strings.TrimSpace(raw) == "" {
		return nil, fmt.Errorf(
			"%s is not set; this command is invoked by kubectl, not directly", execInfoEnvVar)
	}

	var info kubeExecInfo
	if err := json.Unmarshal([]byte(raw), &info); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", execInfoEnvVar, err)
	}

	version := strings.TrimSpace(info.APIVersion)
	if version == "" {
		return nil, fmt.Errorf("%s did not specify an apiVersion", execInfoEnvVar)
	}
	if !supportedExecCredentialAPIVersions[version] {
		return nil, fmt.Errorf(
			"unsupported client authentication apiVersion %q (supported: client.authentication.k8s.io/v1beta1, client.authentication.k8s.io/v1)",
			version)
	}
	info.APIVersion = version
	return &info, nil
}

// writeExecCredential prints the ExecCredential as the sole content of stdout,
// echoing the apiVersion kubectl asked for.
func writeExecCredential(cmd *cobra.Command, cred *k8s.ExecCredential, apiVersion string) error {
	if cred == nil {
		return errors.New("no cluster credential was produced")
	}

	out := k8s.ExecCredential{
		APIVersion: apiVersion,
		Kind:       "ExecCredential",
		Status:     cred.Status,
	}

	data, err := json.Marshal(out)
	if err != nil {
		return fmt.Errorf("failed to encode ExecCredential: %w", err)
	}
	_, err = cmd.OutOrStdout().Write(append(data, '\n'))
	return err
}
