package cmd

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/aaearon/grant-cli/internal/cache"
	"github.com/aaearon/grant-cli/internal/k8s"
	"github.com/cyberark/idsec-sdk-golang/pkg/auth"
	sdkconfig "github.com/cyberark/idsec-sdk-golang/pkg/config"
	authmodels "github.com/cyberark/idsec-sdk-golang/pkg/models/auth"
	"github.com/cyberark/idsec-sdk-golang/pkg/profiles"
	sdkk8s "github.com/cyberark/idsec-sdk-golang/pkg/services/sca/k8s"
	"github.com/spf13/cobra"
)

// execInfoEnvVar is the environment variable kubectl sets for exec credential
// plugins. It carries the requested apiVersion and whether stdin is available.
const execInfoEnvVar = "KUBERNETES_EXEC_INFO"

// supportedExecCredentialAPIVersions are the client-go exec plugin API versions
// grant answers. The response apiVersion always echoes the request.
var supportedExecCredentialAPIVersions = map[string]bool{
	"client.authentication.k8s.io/v1beta1": true,
	"client.authentication.k8s.io/v1":      true,
}

// kubeExecInfo is the subset of KUBERNETES_EXEC_INFO grant reads.
type kubeExecInfo struct {
	APIVersion string `json:"apiVersion"`
	Kind       string `json:"kind"`
	Spec       struct {
		Interactive bool `json:"interactive"`
	} `json:"spec"`
}

// execCredentialFlags are the cluster identifiers embedded in the kubeconfig
// exec stanza.
type execCredentialFlags struct {
	csp            string
	fqdn           string
	roleID         string
	organizationID string
	namespace      string
}

// execCredentialDeps are the authenticated dependencies of the credential flow.
// They are resolved lazily — only after the exec info is validated and the
// credential cache has been consulted — so a cache hit never triggers a login.
type execCredentialDeps struct {
	provider clusterCredentialProvider

	// elevateToken is the Idira session JWT. The Azure providers compare the
	// identity in it against the logged-in Azure CLI account.
	elevateToken string
}

// resolveExecCredentialDeps authenticates and builds the SCA k8s service.
// Overridable for tests.
var resolveExecCredentialDeps = defaultExecCredentialDeps

// newK8sExecCredentialCommand creates the hidden kubectl credential plugin command.
func newK8sExecCredentialCommand(runFn func(*cobra.Command, []string) error) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "exec-credential",
		Short: "kubectl credential plugin (invoked by kubectl, not by hand)",
		Long: `Emit a kubectl ExecCredential for an SCA-eligible cluster.

This command implements the client.authentication.k8s.io exec plugin protocol.
kubectl invokes it via the exec stanza in a kubeconfig generated by
'grant k8s kubeconfig'. It writes nothing to stdout but the ExecCredential JSON;
all diagnostics go to stderr.`,
		Hidden:        true,
		Args:          cobra.NoArgs,
		SilenceErrors: true,
		SilenceUsage:  true,
		RunE:          runFn,
	}

	cmd.Flags().String("csp", "", "Cloud provider: aws, azure")
	cmd.Flags().String("fqdn", "", "Cluster API endpoint FQDN")
	cmd.Flags().String("role-id", "", "Cloud role ID to elevate")
	cmd.Flags().String("organization-id", "", "Azure Entra directory (tenant) ID or AWS organization ID")
	cmd.Flags().String("namespace", "", "Kubernetes namespace (Azure namespace-scoped targets)")

	return cmd
}

// NewK8sExecCredentialCommand creates the production exec-credential command.
func NewK8sExecCredentialCommand() *cobra.Command {
	return newK8sExecCredentialCommand(func(cmd *cobra.Command, args []string) error {
		return runK8sExecCredential(cmd, resolveExecCredentialDeps, defaultCredentialCache(), os.Getenv(execInfoEnvVar))
	})
}

// defaultCredentialCache returns the on-disk ExecCredential cache, or nil when
// the cache directory cannot be resolved (credentials are then never cached).
func defaultCredentialCache() *k8s.CredentialCache {
	dir, err := cache.CacheDir()
	if err != nil {
		return nil
	}
	return k8s.NewCredentialCache(dir)
}

// reserveStdoutForProtocol keeps everything except the ExecCredential JSON off
// os.Stdout for the duration of this command. There are two independent writers
// to shut up, and both must be handled:
//
//  1. Loggers. The SDK logger is constructed with log.New(os.Stdout, ...) and
//     resolves its level from IDSEC_LOG_LEVEL on every call, so
//     `grant --verbose k8s exec-credential` would interleave log lines with the
//     credential JSON. Forcing CRITICAL silences every such logger at the source.
//  2. Interactive auth prompts. On a cache miss with stdin available we can reach
//     Authenticate, and the SDK prints its browser-redirect message to os.Stdout
//     unless config.IsStdoutReservedForData() is true — see
//     pkg/auth/identity/idsec_identity.go:546-556. ReserveStdoutForData exists
//     for exactly this case and flips that message to stderr.
//
// When the user asked for verbose output we switch on the SDK's kubectl-login
// diagnostics channel instead, which writes to stderr by design.
//
// Concurrency note: IDSEC_LOG_LEVEL, IDSEC_KUBELOGIN_LOG_LEVEL and the SDK's
// stdout reservation are all process-global. That is safe here because the CLI
// runs a single command per process (same assumption as the `verbose` var in
// root.go). One caveat survives it: a goroutine abandoned by
// k8s.runWithContext can outlive this restore and log late, after the level has
// gone back to INFO. That would land on stdout — but only after the command has
// already written its JSON and returned, so kubectl has its response either way.
func reserveStdoutForProtocol(wantDiagnostics bool) func() {
	prevLevel, hadLevel := os.LookupEnv(sdkconfig.IdsecLogLevelEnvVar)
	sdkconfig.DisableVerboseLogging()

	// Route the SDK's interactive browser/IdP prompts to stderr.
	sdkconfig.ReserveStdoutForData()

	prevKube, hadKube := os.LookupEnv(sdkk8s.KubectlLoginLogLevelEnvVar)
	if wantDiagnostics {
		_ = os.Setenv(sdkk8s.KubectlLoginLogLevelEnvVar, "INFO")
	}

	return func() {
		sdkconfig.ReleaseStdoutForData()
		restoreEnv(sdkconfig.IdsecLogLevelEnvVar, prevLevel, hadLevel)
		if wantDiagnostics {
			restoreEnv(sdkk8s.KubectlLoginLogLevelEnvVar, prevKube, hadKube)
		}
	}
}

func restoreEnv(key, value string, had bool) {
	if had {
		_ = os.Setenv(key, value)
		return
	}
	_ = os.Unsetenv(key)
}

// runK8sExecCredential emits the ExecCredential JSON on stdout and nothing else.
//
// Order matters: the exec info and flags are validated, then the credential cache
// is consulted, and only on a miss is authentication attempted. A cache hit must
// never trigger a login prompt — kubectl may be running with no terminal at all.
func runK8sExecCredential(
	cmd *cobra.Command,
	resolveDeps func(interactive bool) (*execCredentialDeps, error),
	credCache *k8s.CredentialCache,
	rawExecInfo string,
) error {
	restore := reserveStdoutForProtocol(verbose)
	defer restore()

	info, err := parseExecInfo(rawExecInfo)
	if err != nil {
		return err
	}

	flags := parseExecCredentialFlags(cmd)
	if strings.TrimSpace(flags.fqdn) == "" {
		return errors.New("--fqdn is required; regenerate your kubeconfig with 'grant k8s kubeconfig'")
	}
	if _, err := k8s.NormalizeCSP(flags.csp); err != nil {
		return err
	}

	key := k8s.CredentialKey{
		CSP:            flags.csp,
		FQDN:           flags.fqdn,
		RoleID:         flags.roleID,
		Namespace:      flags.namespace,
		OrganizationID: flags.organizationID,
	}

	// Cache first, before any authentication.
	if credCache != nil {
		// Rejecting an entry degrades into a fresh login; say why, on stderr.
		credCache.Warn = func(msg string) {
			fmt.Fprintf(cmd.ErrOrStderr(), "Warning: %s\n", msg)
		}
		if cred, ok := credCache.Get(key); ok {
			execDiag(cmd, "reusing cached cluster credential for %s", flags.fqdn)
			return writeExecCredential(cmd, cred, info.APIVersion)
		}
	}

	deps, err := resolveDeps(info.Spec.Interactive)
	if err != nil {
		return err
	}

	ctx, cancel := context.WithTimeout(context.Background(), apiTimeout)
	defer cancel()

	cred, err := deps.provider.ExecCredential(ctx, k8s.ExecCredentialParams{
		CSP:            flags.csp,
		FQDN:           flags.fqdn,
		RoleID:         flags.roleID,
		OrganizationID: flags.organizationID,
		Namespace:      flags.namespace,
		ElevateToken:   deps.elevateToken,
		Interactive:    info.Spec.Interactive,
		Diagnostics:    verbose,
	})
	if err != nil {
		return err
	}

	if credCache != nil {
		if err := credCache.Put(key, cred); err != nil {
			execDiag(cmd, "failed to cache cluster credential: %v", err)
		}
	}

	return writeExecCredential(cmd, cred, info.APIVersion)
}

// execDiag writes a verbose diagnostic to stderr. It deliberately bypasses the
// package-level `log`, whose SDK backend writes to stdout.
func execDiag(cmd *cobra.Command, format string, args ...any) {
	if !verbose {
		return
	}
	fmt.Fprintf(cmd.ErrOrStderr(), "grant k8s exec-credential | "+format+"\n", args...)
}

// defaultExecCredentialDeps authenticates without prompting where possible.
//
// A cached, still-valid Idira token is used as-is. Only when there is none does
// it fall back to an interactive Authenticate — and when kubectl reported that
// stdin is unavailable it refuses instead, because a browser or MFA prompt from
// inside a kubectl invocation would hang.
func defaultExecCredentialDeps(interactive bool) (*execCredentialDeps, error) {
	loader := profiles.DefaultProfilesLoader()
	profile, err := (*loader).LoadProfile("grant")
	if err != nil {
		return nil, fmt.Errorf("failed to load profile: %w", err)
	}

	ispAuth := auth.NewIdsecISPAuth(true)

	// LoadAuthentication reads the keyring and may refresh over the network, but
	// never prompts. It signals "no usable session" in more than one way: an
	// absent auth profile yields (nil, nil) (pkg/auth/idsec_auth.go:326), while
	// unusable refresh state yields an error (pkg/auth/idsec_isp_auth.go:144).
	// Both, plus an empty token string, mean the same thing here.
	token, err := ispAuth.LoadAuthentication(profile, true)
	if err != nil || token == nil || strings.TrimSpace(token.Token) == "" {
		if !interactive {
			return nil, fmt.Errorf(
				"%w: no valid cached Idira session and kubectl reported that stdin is unavailable; run 'grant login' in a terminal first",
				k8s.ErrInteractionRequired)
		}
		token, err = ispAuth.Authenticate(profile, nil, &authmodels.IdsecSecret{Secret: ""}, false, false)
		if err != nil {
			return nil, fmt.Errorf("authentication failed: %w", err)
		}
	}
	if token == nil || strings.TrimSpace(token.Token) == "" {
		return nil, errors.New("authentication produced no session token, run 'grant login'")
	}

	svc, err := k8s.NewService(ispAuth)
	if err != nil {
		return nil, fmt.Errorf("failed to create SCA k8s service: %w", err)
	}

	return &execCredentialDeps{provider: svc, elevateToken: token.Token}, nil
}

func parseExecCredentialFlags(cmd *cobra.Command) execCredentialFlags {
	var f execCredentialFlags
	f.csp, _ = cmd.Flags().GetString("csp")
	f.fqdn, _ = cmd.Flags().GetString("fqdn")
	f.roleID, _ = cmd.Flags().GetString("role-id")
	f.organizationID, _ = cmd.Flags().GetString("organization-id")
	f.namespace, _ = cmd.Flags().GetString("namespace")
	return f
}

// parseExecInfo reads KUBERNETES_EXEC_INFO and validates the requested apiVersion.
func parseExecInfo(raw string) (*kubeExecInfo, error) {
	if strings.TrimSpace(raw) == "" {
		return nil, fmt.Errorf(
			"%s is not set; this command is invoked by kubectl, not directly", execInfoEnvVar)
	}

	var info kubeExecInfo
	if err := json.Unmarshal([]byte(raw), &info); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", execInfoEnvVar, err)
	}

	version := strings.TrimSpace(info.APIVersion)
	if version == "" {
		return nil, fmt.Errorf("%s did not specify an apiVersion", execInfoEnvVar)
	}
	if !supportedExecCredentialAPIVersions[version] {
		return nil, fmt.Errorf(
			"unsupported client authentication apiVersion %q (supported: client.authentication.k8s.io/v1beta1, client.authentication.k8s.io/v1)",
			version)
	}
	info.APIVersion = version
	return &info, nil
}

// writeExecCredential prints the ExecCredential as the sole content of stdout,
// echoing the apiVersion kubectl asked for.
func writeExecCredential(cmd *cobra.Command, cred *k8s.ExecCredential, apiVersion string) error {
	if cred == nil {
		return errors.New("no cluster credential was produced")
	}

	out := k8s.ExecCredential{
		APIVersion: apiVersion,
		Kind:       "ExecCredential",
		Status:     cred.Status,
	}

	data, err := json.Marshal(out)
	if err != nil {
		return fmt.Errorf("failed to encode ExecCredential: %w", err)
	}
	_, err = cmd.OutOrStdout().Write(append(data, '\n'))
	return err
}
